# Generated by Django 5.2.5 on 2025-09-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
