# Generated by Django 5.2.5 on 2025-09-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_seed_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('webinar', 'Webinar'), ('conference', 'Conference'), ('workshop', 'Workshop'), ('meetup', 'Meetup')], default='conference', max_length=20)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('business', 'Business'), ('innovation', 'Innovation'), ('networking', 'Networking')], default='tech', max_length=20)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.URLField(max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('registration_link', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
